#!/bin/bash
WORKSPACE=$1
DOCKERFILE=$2
IMAGE_NAME=$3
IMAGE_VERSION=$4
REPO_URL=$5

FULL_IMAGE_NAME="${WORKSPACE}-${IMAGE_NAME}"

sudo docker build -t ${FULL_IMAGE_NAME}:${IMAGE_VERSION} --build-arg NAME_SPACE=${WORKSPACE} -f ${DOCKERFILE} .
sudo docker tag ${FULL_IMAGE_NAME}:${IMAGE_VERSION} ${REPO_URL}/${FULL_IMAGE_NAME}:${IMAGE_VERSION}
sudo docker push ${REPO_URL}/${FULL_IMAGE_NAME}:${IMAGE_VERSION}