pipeline {
    agent any
    parameters {
        choice(name: 'WORKSPACE', choices: ['develop', 'products'], description: 'Môi trường build')
        string(name: 'IMAGES', defaultValue: 'llm-gateway', description: 'Tên image')
        string(name: 'DOCKERFILE', defaultValue: 'Dockerfile', description: 'Đường dẫn Dockerfile')
        string(name: 'DEPLOYMENT', defaultValue: 'llm-gateway', description: 'Tên deployment trên K8s')
        string(name: 'K8SCLS', defaultValue: 'devk8scls2', description: 'Tên cluster K8s')
        string(name: 'URL_PRIVATE_REGISTRY', defaultValue: 'dockerhub.finhay.lan', description: 'URL private registry')
    }
    environment {
        BRANCH_NAME = "${GIT_BRANCH.split("/")[1]}"
    }
    stages {
        stage('load env') {
            steps {
                script {
                    try {
                        if (params.WORKSPACE == "develop") {
                            sh """
                                sudo cp ./env/${params.WORKSPACE}.${params.IMAGES}.env ./.env || true
                                ls -lah
                            """
                        }
                        if (params.WORKSPACE == "products") {
                            echo "Products environment - do nothing!"
                        }
                    }
                    catch (err) {
                        currentBuild.result = "FAILED"
                        throw err
                    }
                }
            }
        }
        stage('Build and upload image') {
            steps {
                script {
                    try {
                        sh "bash ./cicd/build_image.sh ${params.WORKSPACE} ${params.DOCKERFILE} ${params.IMAGES} ${BUILD_NUMBER} ${params.URL_PRIVATE_REGISTRY}"
                        sh "sudo docker images \"${params.URL_PRIVATE_REGISTRY}/${params.WORKSPACE}-${params.IMAGES}\" --digests"
                    }
                    catch (err) {
                        currentBuild.result = "FAILED"
                        throw err
                    }
                }
            }
        }
        stage('Promote to Develop') {
            steps {
                script {
                    try {
                        def deploymentName = "${params.WORKSPACE}-${params.IMAGES}"
                        sh "bash ./cicd/update_image_to_service_on_k8s.sh ${params.K8SCLS} ${params.WORKSPACE} ${deploymentName} ${params.IMAGES} ${BUILD_NUMBER} ${params.URL_PRIVATE_REGISTRY}"
                    }
                    catch (err) {
                        currentBuild.result = "FAILED"
                        throw err
                    }
                }
            }
        }
    }
    post {
        always {
            script {
                env.GIT_COMMIT_MSG = sh (script: 'git log -1 --pretty=%B ${GIT_COMMIT}', returnStdout: true).trim()
                env.GIT_AUTHOR = sh (script: 'git log -1 --pretty=%an ${GIT_COMMIT}', returnStdout: true).trim()
                def buildStatus = currentBuild.result ?: 'SUCCESS'
                def environmentName = "${params.K8SCLS}-${params.WORKSPACE}"
                echo "Sending notification to Google Chat..."
                sh """
                    bash ./cicd/send-noti-to-ggchat.sh \
                        '${buildStatus}' \
                        '${BUILD_NUMBER}' \
                        '${params.IMAGES}' \
                        '${environmentName}' \
                        '${env.GIT_COMMIT_MSG}' \
                        '${BUILD_URL}' \
                        '${env.GIT_AUTHOR}' \
                        '${BRANCH_NAME}'
                """
            }
        }
    }
}